steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zoi1-367520/zoi1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/zoi1-367520/zoi1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'zoi1', '--image', 'gcr.io/zoi1-367520/zoi1', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/zoi1-367520/zoi1